FROM openjdk

#ARG JAR_FILE=../build/libs/loginDB-0.0.1-SNAPSHOT.jar
#ARG JAR_FILE=/Users/lee-macbook/Desktop/docker-compose/loginDB/build/libs

#COPY ${JAR_FILE} /app/app.jar

CMD ["java", "-jar","/app/loginDB-0.0.1-SNAPSHOT.jar"]