version: "3"
services:
  mysql:
    image: mysql
    volumes_from:
      - dockerVolume02
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3307:3306"